### ISSUE TITLE
题目写错了，看的时候一直没理解，找来了剑指offer原文才理解

### ISSUE THREAD

**Issue by irezm** [todorex/Coding-Interviews#2]
https://github.com/todorex/Coding-Interviews/blob/master/notes/%E6%95%B0%E7%BB%84%E4%B8%AD%E9%87%8D%E5%A4%8D%E7%9A%84%E6%95%B0%E5%AD%97.md#%E9%A2%98%E7%9B%AE%E6%8F%8F%E8%BF%B0
题目中是 {2, 3, 1, 0, 2, 5,3}，你写成 {2, 3, 1, 0, 2, 5}了

**Comment by todorex** [comment]
@irezm 谢了，我改一下

**Comment by irezm** [comment]
> @irezm谢了，我改一下
客气，刚开始学，有点蒙，感谢你的教程
