### ISSUE TITLE
用栈实现队列的代码中有个Bug

### ISSUE THREAD

**Issue by LiYinJiang** [todorex/Coding-Interviews#3]
public int pop() throws Exception {
        if (stack2.isEmpty()) {
            while (!stack1.isEmpty()) {
                stack2.push(stack1.pop());
            }
        }

        if (stack1.isEmpty()) {
            throw new Exception("queue is empty");

        }
        return stack2.pop();

    }
百分百抛Bug

**Comment by todorex** [comment]
@LiYinJiang 确实，应该是   
```
 if (stack2.isEmpty()) {
        throw new Exception("queue is empty");
 }
```
你提个pr吧

**Comment by todorex** [comment]
pr修复
